volumes:
  kukudb:
    driver: local

services:
  kukudata:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_USERNAME=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#      - MYSQL_ROOT_URL=${DB_URL}
      - MYSQL_DATABASE=kukushop
    ports:
      - 3307:3306
    volumes:
      - kukudb:/var/lib/mysql
